apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qypc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-qypc@sha256:b1d583a455610588a8dd1ff7389a74a43bd7f2c32694ffb69f4617d8f3c84bab
        name: my-nodejs
        resources: {}
status: {}
